import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import './globals.css';
import {CartProvider} from '@/hooks/useCart';
import NextUIProv from './NextUIProv';

const inter=Inter({subsets: ['latin']});

export const metadata: Metadata={
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode|any;
}

const RootLayout: React.FC<RootLayoutProps>=({children}) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
          <NextUIProv>
            {children}
          </NextUIProv>
        </CartProvider>
      </body>
    </html>
  );
};

export default RootLayout;
